# Use the latest MySQL base image
FROM mysql:latest

# Set environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=accwe-hospital

# Expose the MySQL port
EXPOSE 3306

# Command to be executed when the container starts
CMD ["mysqld"]